/* tslint:disable */
/* eslint-disable */
/**
 * AAA
 * API for the AAA service
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Response,
} from '../models';
import {
    ResponseFromJSON,
    ResponseToJSON,
} from '../models';

/**
 * 
 */
export class NotTheRealNameApi extends runtime.BaseAPI {

    /**
     */
    async getUserInfoHelloRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/get-response`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseFromJSON(jsonValue));
    }

    /**
     */
    async getUserInfoHello(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Response> {
        const response = await this.getUserInfoHelloRaw(initOverrides);
        return await response.value();
    }

}
